name: Deploy na jakebrno.cz

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Upload via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: 62.109.154.45
          username: jakebrno.cz
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./
          server-dir: /public_html/
          passive: false
          exclude: |
            **/.git*
            **/.git*/**
            .github/**
            *.md
